ALTER TABLE auth_users ADD COLUMN mfa_secret VARCHAR(64);
ALTER TABLE auth_users ADD COLUMN mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE auth_users ADD COLUMN failed_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE auth_users ADD COLUMN locked_until TIMESTAMP WITH TIME ZONE;
