ALTER TABLE terminals ADD COLUMN IF NOT EXISTS m_key VARCHAR(64);
ALTER TABLE terminals ADD COLUMN IF NOT EXISTS pik VARCHAR(64);
ALTER TABLE terminals ADD COLUMN IF NOT EXISTS mak VARCHAR(64);
ALTER TABLE terminals ADD COLUMN IF NOT EXISTS last_activity_at TIMESTAMP WITH TIME ZONE;
