spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  kafka:
    producer:
      retries: 3
      properties:
        max.block.ms: 10000

logging:
  level:
    com.switchplatform: WARN

management:
  endpoint:
    health:
      show-details: never
